services:
    postgres:
        image: postgres:18
        container_name: postgres18
        restart: unless-stopped

        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            APP_DB_USER: ${APP_DB_USER}
            APP_DB_PASSWORD: ${APP_DB_PASSWORD}

        ports:
            - "5432:5432"

        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init_db:/docker-entrypoint-initdb.d
            - ./backup:/backup

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    ofelia:
        container_name: ofelia
        image: mcuadros/ofelia:latest
        depends_on:
            - postgres
        command: daemon --docker

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./ofelia/ofelia.conf:/etc/ofelia.conf:ro

volumes:
    postgres_data:
