name: Deploy to MSK_VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Debug information
              run: |
                echo "Creating .ssh directory..."
                mkdir -p $HOME/.ssh
                echo "Directory created, listing:"
                ls -la $HOME/.ssh
                echo "Setting permissions..."
                chmod 700 $HOME/.ssh
                echo "Testing write access..."
                touch $HOME/.ssh/test_file
                ls -la $HOME/.ssh/
                rm $HOME/.ssh/test_file
                echo "SSH directory setup completed successfully"
                echo "${{ secrets.MSK_VPS_KEY }}" > ~/.ssh/id_ed25519
                chmod 600 ~/.ssh/id_ed25519
                ssh-keyscan -H ${{ secrets.MSK_VPS_HOST }} >> ~/.ssh/known_hosts

            # - name: Setup SSH
            #   run: |
            #     echo "${{ secrets.MSK_VPS_KEY }}" > ~/.ssh/id_ed25519
            #     chmod 600 ~/.ssh/id_ed25519
            #     ssh-keyscan -H ${{ secrets.MSK_VPS_HOST }} >> ~/.ssh/known_hosts

            # - name: Deploy to VPS
            #   run: |
            #     ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.MSK_VPS_PORT }} ${{ secrets.MSK_VPS_USER }}@${{ secrets.MSK_VPS_HOST }} << 'EOF'
            #     cd /srv/weight_log_bot
            #     git pull origin main
            #     docker compose up --build -d
            #     EOF
