name: Deploy to MSK_VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - run: mkdir $HOME/.ssh
            - run: echo "1"
            - run: chmod 700 $HOME/.ssh
            - run: echo "2"
            - run: echo "${{ secrets.MSK_VPS_KEY }}" > $HOME/.ssh/id_ed25519
            - run: echo "3"
            - run: chmod 600 $HOME/.ssh/id_ed25519
            - run: echo "4"
            - run: ssh-keyscan -H ${{ secrets.MSK_VPS_HOST }} >> $HOME/.ssh/known_hosts
            - run: echo "5"
