name: Deploy to MSK_VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH
              run: |
                mkdir $HOME/.ssh
                ls -la $HOME/
                chmod 700 $HOME/.ssh
                echo "${{ secrets.MSK_VPS_KEY }}" > $HOME/.ssh/id_ed25519
                chmod 600 $HOME/.ssh/id_ed25519
                ssh-keyscan -H ${{ secrets.MSK_VPS_HOST }} >> $HOME/.ssh/known_hosts
                echo "success"
