name: Deploy to MSK_VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH
              run: |
                mkdir -p $HOME/.ssh
                chmod 700 $HOME/.ssh
                echo "${{ secrets.MSK_VPS_KEY }}" > $HOME/.ssh/id_ed25519
                chmod 600 $HOME/.ssh/id_ed25519
                ssh-keyscan -H ${{ secrets.MSK_VPS_HOST }} >> $HOME/.ssh/known_hosts

            - name: Deploy to VPS
              run: |
                ssh -i ~/.ssh/id_ed25519 \
                    -p ${{ secrets.MSK_VPS_PORT }} \
                    -o StrictHostKeyChecking=no \
                    -o ConnectTimeout=30 \
                    -o LogLevel=ERROR \
                    ${{ secrets.MSK_VPS_USER }}@${{ secrets.MSK_VPS_HOST }} << 'EOF'
                echo 'Connected successfully!'
                cd /srv/weight_log_bot
                git pull origin main
                docker compose up --build -d
                EOF
