name: Deploy to MSK_VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Debug information
              run: |
                mkdir -p $HOME/.ssh
                chmod 700 $HOME/.ssh
                echo "Testing key writing..."
                KEY_CONTENT="${{ secrets.MSK_VPS_KEY }}"
                echo "Key length: ${#KEY_CONTENT}"
                echo "First 50 chars: ${KEY_CONTENT:0:50}"
                echo "Trying to write key file..."
                
                echo "${{ secrets.MSK_VPS_KEY }}" > $HOME/.ssh/id_ed25519
                echo "Write completed, exit code: $?"
                echo "File size: $(wc -c < $HOME/.ssh/id_ed25519)"
                ls -la $HOME/.ssh/id_ed25519
                
                chmod 600 $HOME/.ssh/id_ed25519
                echo "Chmod completed, exit code: $?"
